import type { Cinema } from "./types";

export const CINEMAS: Cinema[] = [
  {
    id: "tjoy-yokohama",
    name: "T・ジョイ横浜",
    shortName: "T・ジョイ横浜",
    area: "yokohama",
    areaLabel: "横浜駅",
    address: "横浜市西区南幸1-1-1 JR横浜タワー8F",
    latitude: 35.46572,
    longitude: 139.62236,
    sourceUrl: "https://tjoy.jp/t-joy_yokohama",
    activeUntil: null,
    approval: "private_only",
    nearestStationId: "yokohama",
    stationWalkMinutes: 2,
    stationWalkDistanceMeters: 80,
  },
  {
    id: "movil",
    name: "ムービル",
    shortName: "ムービル",
    area: "yokohama",
    areaLabel: "横浜駅",
    address: "横浜市西区南幸2-1-22",
    latitude: 35.46312,
    longitude: 139.61784,
    sourceUrl: "https://109cinemas.net/movil/",
    activeUntil: "2026-09-30",
    approval: "private_only",
    nearestStationId: "yokohama",
    stationWalkMinutes: 10,
    stationWalkDistanceMeters: 699,
  },
  {
    id: "yokohama-burg13",
    name: "横浜ブルク13",
    shortName: "横浜ブルク13",
    area: "minatomirai",
    areaLabel: "桜木町",
    address: "横浜市中区桜木町1-1-7 コレットマーレ6F",
    latitude: 35.45125,
    longitude: 139.63084,
    sourceUrl: "https://tjoy.jp/yokohama_burg13",
    activeUntil: null,
    approval: "private_only",
    nearestStationId: "sakuragicho",
    stationWalkMinutes: 2,
    stationWalkDistanceMeters: 148,
  },
  {
    id: "aeon-minatomirai",
    name: "イオンシネマみなとみらい",
    shortName: "イオンシネマ",
    area: "minatomirai",
    areaLabel: "みなとみらい",
    address: "横浜市中区新港2-2-1 横浜ワールドポーターズ5F",
    latitude: 35.45518,
    longitude: 139.63896,
    sourceUrl: "https://theater.aeoncinema.com/theaters/minatomirai/",
    activeUntil: null,
    approval: "private_only",
    nearestStationId: "minatomirai",
    stationWalkMinutes: 11,
    stationWalkDistanceMeters: 777,
  },
  {
    id: "united-minatomirai",
    name: "ローソン・ユナイテッドシネマ STYLE-S みなとみらい",
    shortName: "ユナイテッドシネマ",
    area: "minatomirai",
    areaLabel: "みなとみらい",
    address: "横浜市西区みなとみらい3-5-1 MARK IS みなとみらい",
    latitude: 35.45774,
    longitude: 139.63248,
    sourceUrl: "https://www.unitedcinemas.jp/minatomirai/daily.php",
    activeUntil: null,
    approval: "private_only",
    nearestStationId: "minatomirai",
    stationWalkMinutes: 3,
    stationWalkDistanceMeters: 163,
  },
  {
    id: "kino-minatomirai",
    name: "kino cinéma横浜みなとみらい",
    shortName: "kino cinéma",
    area: "minatomirai",
    areaLabel: "みなとみらい",
    address: "横浜市西区みなとみらい4-7-1 みなとみらいミッドスクエア2F",
    latitude: 35.4591,
    longitude: 139.62801,
    sourceUrl: "https://kinocinema.jp/minatomirai/",
    activeUntil: null,
    approval: "private_only",
    nearestStationId: "minatomirai",
    stationWalkMinutes: 9,
    stationWalkDistanceMeters: 601,
  },
  {
    id: "cinemarine",
    name: "横浜シネマリン",
    shortName: "横浜シネマリン",
    area: "kannai",
    areaLabel: "関内・伊勢佐木町",
    address: "横浜市中区長者町6-95",
    latitude: 35.44285,
    longitude: 139.63015,
    sourceUrl: "https://cinemarine.co.jp/",
    activeUntil: null,
    approval: "private_only",
    nearestStationId: "isezakichojamachi",
    stationWalkMinutes: 6,
    stationWalkDistanceMeters: 350,
  },
  {
    id: "jack-and-betty",
    name: "シネマ・ジャック＆ベティ",
    shortName: "ジャック＆ベティ",
    area: "kannai",
    areaLabel: "関内・伊勢佐木町",
    address: "横浜市中区若葉町3-51",
    latitude: 35.44018,
    longitude: 139.62585,
    sourceUrl: "https://www.jackandbetty.net/",
    activeUntil: null,
    approval: "private_only",
    nearestStationId: "koganecho",
    stationWalkMinutes: 6,
    stationWalkDistanceMeters: 395,
  },
  {
    id: "novecento",
    name: "シネマノヴェチェント",
    shortName: "ノヴェチェント",
    area: "tobe",
    areaLabel: "戸部・西横浜",
    address: "横浜市西区中央2-1-8 岩崎ビル2F",
    latitude: 35.45344,
    longitude: 139.61157,
    sourceUrl: "https://cinema1900.wixsite.com/home/filmtheater1900",
    activeUntil: "2026-08-31",
    approval: "private_only",
    nearestStationId: "tobe",
    stationWalkMinutes: 14,
    stationWalkDistanceMeters: 925,
  },
];

export function getCinema(id: string): Cinema {
  const cinema = CINEMAS.find((item) => item.id === id);
  if (!cinema) {
    throw new Error(`Unknown cinema: ${id}`);
  }
  return cinema;
}
