/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false --env-interface=ScheduleEnv worker/env.d.ts` (hash: d76153e24245da80a63bb7b98effc332)
interface __BaseEnv_ScheduleEnv {
	DB: D1Database;
	BROWSER: BrowserRun;
	AI: Ai;
	SCHEDULE_DAYS: "7";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry");
	}
	interface Env extends __BaseEnv_ScheduleEnv {}
}
interface ScheduleEnv extends __BaseEnv_ScheduleEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SCHEDULE_DAYS">> {}
}
